version: "3.8"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: demo_app
    ports:
      - "8080:8080" # Standard Spring Boot port
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db.wrkgtiebypclbachhbmk.supabase.co:5432/postgres
      - SPRING_DATASOURCE_USERNAME=postgres
      # Consider using a .env file for sensitive data mainly
      - SPRING_DATASOURCE_PASSWORD=duAoZfAw4L1DGJIF
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    # depends_on:
    #   - redis

  # redis:
  #   image: redis:7-alpine
  #   container_name: demo_redis
  #   ports:
  #     - "6379:6379"
  #   restart: unless-stopped
